[package]
name = "fast-table-widget"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/airstrike/iced.git", branch = "latest", version = "0.14.0-dev", features = ["lazy", "advanced", "debug"] }
