[package]
name = "tabular"
version = "0.2.0"
edition = "2024"

[features]
serde = ["dep:serde"]

[dependencies]
iced = { version = "0.13", features = ["lazy", "advanced", "debug"] }
serde = { version = "1", optional = true, features = ["derive"] }
